#!/usr/bin/env bash
# deploy/google-cloud/setup-storage.sh — One-time GCS bucket + service account setup for Cloud Run.
# [Sync] 2026-06-12: point follow-up release guidance to deploy/google-cloud/deploy.sh.
# [Sync] 2026-06-12: move Google Cloud implementation from deploy/ to deploy/google-cloud/.
#
# Run this ONCE before the first deploy. It is safe to re-run (idempotent).
#
# Usage:
#   export GCP_PROJECT_ID=your-project-id
#   ./deploy/google-cloud/setup-storage.sh
#
# Optional overrides:
#   GCP_REGION          default: asia-east1
#   BUCKET_NAME         default: ink-memory-data-<PROJECT_ID>
#   SA_NAME             default: ink-backend-sa
#   BACKEND_SERVICE     default: ink-backend
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# ── Config ───────────────────────────────────────────────────────────────────
PROJECT_ID="${GCP_PROJECT_ID:?ERROR: GCP_PROJECT_ID is not set. Run: export GCP_PROJECT_ID=your-project-id}"
REGION="${GCP_REGION:-asia-east1}"
BUCKET_NAME="${BUCKET_NAME:-ink-memory-data-${PROJECT_ID}}"
SA_NAME="${SA_NAME:-ink-backend-sa}"
SA_EMAIL="${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
BACKEND_SERVICE="${BACKEND_SERVICE:-ink-backend}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[setup]${NC} $*"; }
info() { echo -e "${CYAN}[info]${NC}  $*"; }
warn() { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()  { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

command -v gcloud >/dev/null 2>&1 || err "gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install"

log "Project : ${PROJECT_ID}"
log "Region  : ${REGION}"
log "Bucket  : gs://${BUCKET_NAME}"
log "SA      : ${SA_EMAIL}"
echo ""

# ── Step 1: set project ───────────────────────────────────────────────────────
gcloud config set project "${PROJECT_ID}" --quiet

# ── Step 2: enable required APIs ─────────────────────────────────────────────
log "Enabling required APIs..."
gcloud services enable \
  storage.googleapis.com \
  run.googleapis.com \
  iam.googleapis.com \
  --project="${PROJECT_ID}"

# ── Step 3: create GCS bucket ────────────────────────────────────────────────
log "Creating GCS bucket gs://${BUCKET_NAME} in ${REGION}..."
if gsutil ls -b "gs://${BUCKET_NAME}" &>/dev/null; then
  log "Bucket already exists, skipping."
else
  gsutil mb \
    -p "${PROJECT_ID}" \
    -l "${REGION}" \
    -b on \
    "gs://${BUCKET_NAME}"
  log "Bucket created."
fi

# Prevent public access
gsutil pap set enforced "gs://${BUCKET_NAME}" 2>/dev/null || true

# Enable versioning to protect against accidental overwrites
gsutil versioning set on "gs://${BUCKET_NAME}"
log "Versioning enabled on bucket."

# Pre-create the data sub-directories as empty placeholder objects
for dir in file-storage agent-workspace; do
  if ! gsutil ls "gs://${BUCKET_NAME}/${dir}/" &>/dev/null; then
    echo "" | gsutil cp - "gs://${BUCKET_NAME}/${dir}/.keep"
    log "Created placeholder: ${dir}/"
  fi
done

# ── Step 4: create dedicated service account ─────────────────────────────────
log "Creating service account ${SA_NAME}..."
if gcloud iam service-accounts describe "${SA_EMAIL}" \
      --project="${PROJECT_ID}" &>/dev/null; then
  log "Service account already exists, skipping."
else
  gcloud iam service-accounts create "${SA_NAME}" \
    --display-name="Ink & Memory backend runtime SA" \
    --project="${PROJECT_ID}"
  log "Service account created."
fi

# ── Step 5: grant Storage Object Admin on the bucket ─────────────────────────
log "Granting Storage Object Admin on gs://${BUCKET_NAME} to ${SA_EMAIL}..."
gsutil iam ch \
  "serviceAccount:${SA_EMAIL}:roles/storage.objectAdmin" \
  "gs://${BUCKET_NAME}"
log "IAM binding applied."

# ── Step 6: allow the SA to run as itself on Cloud Run ───────────────────────
log "Granting Service Account Token Creator (for self-impersonation)..."
gcloud iam service-accounts add-iam-policy-binding "${SA_EMAIL}" \
  --member="serviceAccount:${SA_EMAIL}" \
  --role="roles/iam.serviceAccountTokenCreator" \
  --condition=None \
  --project="${PROJECT_ID}" \
  --quiet

# ── Step 7: write .storage-env (consumed by deploy.sh) ───────────────────────
ENV_FILE="${REPO_ROOT}/.storage-env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup-storage.sh — do NOT commit this file.
GCS_BUCKET=${BUCKET_NAME}
SA_EMAIL=${SA_EMAIL}
EOF
log "Saved config to ${ENV_FILE}"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
info "════════════════════════════════════════════════════════"
info "  Storage setup complete."
info ""
info "  Bucket  : gs://${BUCKET_NAME}"
info "  SA      : ${SA_EMAIL}"
info ""
info "  Next step: run ./deploy/google-cloud/deploy.sh deploy to build and deploy the app."
info "════════════════════════════════════════════════════════"
echo ""
warn "SQLite WAL mode note:"
warn "  Cloud Storage FUSE supports SQLite but WAL creates extra .db-wal/.db-shm"
warn "  files. Keep backend min-instances=1 to avoid multi-instance write conflicts."
